language: python
python:
- '3.4'
install:
- sudo apt-get update -qq
- sudo apt-get install -qq help2man texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texinfo mercurial
- pip install sphinx
- pip install sphinx_bootstrap_theme
script:
- ./pull-examples.sh
- GH_USER=LoyolaChicagoBooks GH_REPO=distributedsystems "./gh-pages.sh"
env:
  global:
    secure: "DNfQsosCIhRerk/X392/V9wUCYMj/2YxxmJTKQi9HGd0qBOaqWdujM3eJV+Dhp+s+UErWv9+ifQhd9/xAG302z1I5zg3KIiZdBew00wyIbykhXUQHnqZGiZPP7U9QOke9EPShzF4a+QzzgMeNDT+0lcatOUNwg9wmeP6KzdngNQ="
